# Cài đặt chung của plugin TuTienHi
settings:
  # Số tick (20 tick = 1 giây) để chạy vòng lặp tu luyện (tăng linh khí, tạo hiệu ứng)
  cultivation-tick-rate: 20
  # Hiệu ứng hạt khi tu luyện
  particle-effect:
    # Tên hiệu ứng particle của Minecraft. Danh sách: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    name: "CLOUD"
    # Số lượng hạt sinh ra mỗi lần
    count: 10
    # Bán kính vòng tròn hiệu ứng
    radius: 1.0

# Tất cả các tin nhắn của plugin
messages:
  prefix: "&b&lTuTiênHi &r&f» "
  no-permission: "&cBạn không có quyền để sử dụng lệnh này."
  player-only-command: "&cLệnh này chỉ có thể được sử dụng bởi người chơi."
  reload-success: "&aĐã tải lại tất cả các file cấu hình của TuTienHi!"
  
  # Lệnh /tuluyen
  cultivate-start: "&aBạn đã tiến vào trạng thái tu luyện. Ngưng thần tĩnh khí, hấp thụ linh khí trời đất!"
  cultivate-stop: "&eBạn đã thoát khỏi trạng thái tu luyện."
  already-cultivating: "&cBạn đang trong trạng thái tu luyện rồi."
  
  # Lệnh /dotpha
  breakthrough-success: "&d&lCHÚC MỪNG! &fBạn đã đột phá thành công, cảnh giới hiện tại: &b%new_realm_name%"
  breakthrough-fail-not-enough-linh-khi: "&cLinh khí chưa đủ, không thể đột phá! Cần &e%required%&c, hiện có &e%current%&c."
  breakthrough-fail-max-level: "&6Bạn đã đạt đến cảnh giới cao nhất, không thể đột phá nữa!"
  
  # Scoreboard
  scoreboard:
    title: "&b&lTU TIÊN HI"
    lines:
      - "&f"
      - "&eNgười chơi: &f%player_name%"
      - "&eCảnh Giới: &f%realm_name%"
      - "&eLinh Khí: &b%linh_khi%&f/&b%max_linh_khi%"
      - ""
      - "&7v1.0.0"