# ... các cài đặt cũ ...

# Tat ca cac tin nhan cua plugin
messages:
  prefix: "&b&lTuTienHi &r&f» "
  no-permission: "&cBan khong co quyen de su dung lenh nay."
  player-only-command: "&cLệnh này chỉ có thể được sử dụng bởi người chơi."
  reload-success: "&aDa tai lai tat ca cac file cau hinh cua TuTienHi!"
  
  # Lenh /tuluyen
  cultivate-start: "&aBan da tien vao trang thai tu luyen. Ngu than tinh khi, hap thu linh khi troi dat!"
  cultivate-stop: "&eBan da thoat khoi trang thai tu luyen."
  already-cultivating: "&cBan dang trong trang thai tu luyen roi."
  
  # Lenh /dotpha
  breakthrough-success: "&d&lCHUC MUNG! &fBan da dot pha thanh cong, canh gioi hien tai: &b%new_realm_name%"
  breakthrough-fail-not-enough-linh-khi: "&cLinh khi chua du, khong the dot pha! Can &e%required%&c, hien co &e%current%&c."
  breakthrough-fail-max-level: "&6Ban da dat den canh gioi cao nhat, khong the dot pha nua!"

  # Vat Pham
  item-usage: "&aBan da su dung &r%item_name%&a va nhan duoc &b+%amount% &alinh khi!"
  item-give-success: "&aDa trao &e%amount% x &r%item_name% &acho nguoi choi &b%player%&a."
  item-not-found: "&cKhong tim thay vat pham voi ID: &e%id%"
  player-not-found: "&cKhong tim thay nguoi choi: &e%player%"
  
  # Shop
  shop-title: "&8Cua Hang Tu Tien"
  not-enough-money: "&cBan khong du tien! Can &e%cost%&c, ban chi co &e%balance%&c."
  purchase-success: "&aBan da mua thanh cong &r%item_name%&a voi gia &e%cost%&a."

  # Con Duong Tu Tap
  cultivation-path-help:
    - "&eChon con duong tu luyen cua ban:"
    - "&c/kiemtu &7- Tro thanh Kiem Tu, bac thay ve kiem phap."
    - "&6/phattu &7- Tro thanh Phat Tu, than the bat hoai."
    - "&5/matu &7- Tro thanh Ma Tu, suc manh huy diet."
  path-chosen: "&aBan da chon con duong &r%path_name%&a. Khong the thay doi!"
  path-already-chosen: "&cBan da chon con duong tu tap roi, khong the thay doi."