name: TuTienHi
version: 2.0.0
main: vn.tutienhi.TuTienHi
api-version: '1.20'
author: T (and Gemini)
description: He thong tu tien dac sac cho server Minecraft.
softdepend: [PlaceholderAPI, Vault] # Thêm Vault để xử lý tiền tệ

commands:
  tuluyen:
    description: Bat dau hoac dung trang thai tu luyen de hap thu linh khi.
    usage: /tuluyen
    aliases: [tl]
  dotpha:
    description: Tien hanh dot pha len canh gioi tiep theo khi du linh khi.
    usage: /dotpha
    aliases: [dp]
  tutienhi:
    description: Lenh quan tri chinh cua plugin TuTienHi.
    usage: /tutienhi <reload|vatpham>
    aliases: [tth]
    permission: tutienhi.admin
  shoptiengioi:
    description: Mo cua hang Tu Tien.
    usage: /shoptiengioi
    aliases: [stg]
  conduongtutap:
    description: Hien thi cac con duong tu tap.
    usage: /conduongtutap
    aliases: [cdtt]
  kiemtu:
    description: Chon con duong Kiem Tu.
    usage: /kiemtu
  phattu:
    description: Chon con duong Phat Tu.
    usage: /phattu
  matu:
    description: Chon con duong Ma Tu.
    usage: /matu

permissions:
  tutienhi.admin:
    description: Cho phep su dung cac lenh quan tri cua TuTienHi.
    default: op