# Tên của kịch bản tự động, sẽ hiển thị trong tab "Actions" của GitHub
name: Build TuTienHi Plugin

# Điều kiện để kịch bản này được kích hoạt
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # ====================================================================
      # SỬA LỖI: Cập nhật lại tên file cho đúng với phiên bản 2.0.0
      # ====================================================================
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TuTienHi-Plugin
          # Đường dẫn đúng phải là TuTienHi-2.0.0.jar
          path: target/TuTienHi-2.0.0.jar 